<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="3" result="Failed" total="3" passed="2" failed="1" inconclusive="0" skipped="0" asserts="3" engine-version="3.8.0.0" clr-version="4.0.30319.42000" start-time="2018-05-28 06:40:23Z" end-time="2018-05-28 06:40:27Z" duration="4.568667">
  <command-line><![CDATA[nunit3-console.exe  Debug/NUnitReportSample.Test.dll]]></command-line>
  <test-suite type="Assembly" id="0-1005" name="NUnitReportSample.Test.dll" fullname="D:\3 Git\NUnitReportSample\packages\NUnit.ConsoleRunner.3.8.0\tools\Debug\NUnitReportSample.Test.dll" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2018-05-28 06:40:24Z" end-time="2018-05-28 06:40:27Z" duration="3.288472" total="3" passed="2" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="3">
    <environment framework-version="3.10.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.14393.0" platform="Win32NT" cwd="D:\3 Git\NUnitReportSample\packages\NUnit.ConsoleRunner.3.8.0\tools" machine-name="7Y62N72" user="thinhnguyen" user-domain="KMS" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="D:\3 Git\NUnitReportSample\packages\NUnit.ConsoleRunner.3.8.0\tools" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="16220" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1006" name="NUnitReportSample" fullname="NUnitReportSample" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2018-05-28 06:40:24Z" end-time="2018-05-28 06:40:27Z" duration="3.261248" total="3" passed="2" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="3">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1007" name="Test" fullname="NUnitReportSample.Test" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2018-05-28 06:40:24Z" end-time="2018-05-28 06:40:27Z" duration="3.260382" total="3" passed="2" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="3">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="0-1000" name="BrowserTest" fullname="NUnitReportSample.Test.BrowserTest" classname="NUnitReportSample.Test.BrowserTest" runstate="Runnable" testcasecount="1" result="Passed" start-time="2018-05-28 06:40:24Z" end-time="2018-05-28 06:40:27Z" duration="3.120942" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="1">
          <test-case id="0-1001" name="ShouldGoToGoogleSite" fullname="NUnitReportSample.Test.BrowserTest.ShouldGoToGoogleSite" methodname="ShouldGoToGoogleSite" classname="NUnitReportSample.Test.BrowserTest" runstate="Runnable" seed="1990890817" result="Passed" start-time="2018-05-28 06:40:24Z" end-time="2018-05-28 06:40:27Z" duration="3.095019" asserts="1" />
        </test-suite>
        <test-suite type="TestFixture" id="0-1002" name="CalculatorTest" fullname="NUnitReportSample.Test.CalculatorTest" classname="NUnitReportSample.Test.CalculatorTest" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2018-05-28 06:40:27Z" end-time="2018-05-28 06:40:27Z" duration="0.125499" total="2" passed="1" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="2">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1003" name="ShouldAddTwoNumbers" fullname="NUnitReportSample.Test.CalculatorTest.ShouldAddTwoNumbers" methodname="ShouldAddTwoNumbers" classname="NUnitReportSample.Test.CalculatorTest" runstate="Runnable" seed="242670711" result="Passed" start-time="2018-05-28 06:40:27Z" end-time="2018-05-28 06:40:27Z" duration="0.034110" asserts="1" />
          <test-case id="0-1004" name="ShouldMultipleTwoNumbers" fullname="NUnitReportSample.Test.CalculatorTest.ShouldMultipleTwoNumbers" methodname="ShouldMultipleTwoNumbers" classname="NUnitReportSample.Test.CalculatorTest" runstate="Runnable" seed="1403458928" result="Failed" start-time="2018-05-28 06:40:27Z" end-time="2018-05-28 06:40:27Z" duration="0.089068" asserts="1">
            <failure>
              <message><![CDATA[  Expected: 20
  But was:  50
]]></message>
              <stack-trace><![CDATA[   at NUnitReportSample.Test.CalculatorTest.ShouldMultipleTwoNumbers() in D:\3 Git\NUnitReportSample\NUnitReportSample.Test\CalculatorTest.cs:line 22
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: 20
  But was:  50
]]></message>
                <stack-trace><![CDATA[   at NUnitReportSample.Test.CalculatorTest.ShouldMultipleTwoNumbers() in D:\3 Git\NUnitReportSample\NUnitReportSample.Test\CalculatorTest.cs:line 22
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>